---
when:
  - event: [pull_request, tag]
  - event: [push, manual, cron]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: assets
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - make doc

  - name: sync
    image: quay.io/thegeeklab/git-batch
    commands:
      - git-batch

  - name: build
    image: quay.io/thegeeklab/hugo:0.151
    commands:
      - hugo --panicOnWarning

  - name: beautify
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - html-beautify -r -f 'public/**/*.html'

  - name: publish
    image: quay.io/thegeeklab/wp-s3-action
    settings:
      access_key:
        from_secret: s3_access_key
      bucket: geekdocs
      delete: true
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      secret_key:
        from_secret: s3_secret_access_key
      source: public/
      strip_prefix: public/
      target: /${CI_REPO_NAME}
    when:
      - event: [tag]
      - event: [push, manual, cron]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success, failure]

depends_on:
  - static
